name: Node CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm run lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
